absingla/contrail-web-core

README.md
Related-Bug: #1392113
Change-Id: I1086d931237fb1e50b1486708cfc1a6cea68e543
=> Updating README.md file with redis authentication information.

src/serverroot/common/jsondiff.js, src/serverroot/utils/common.utils.js
Handling configDelete key in json diff vector list.
Change-Id: I464cae395de7e85147fc333f7727e07be6afdd94
Related-Bug: #1432564
=> Correcting typo error (apiDelele -> apiDelete)

webroot/js/analyzer-utils.js
When the srcIP/destIp matches with the default gateway or DNS server then we are not showing any path in UI,now we will display a link to vRouter and back to the same VM
to handle this case need to send the nodeIP to webserver
Change-Id: Iaa90d4232065d2265cf7540f1da1d72bb5eff706
=> Reladted-Bug:#1451785

README.md
Bug: 1322424
Change-Id: I7434b137099b45606007537ce2e12b07e62764c6
=> Removing extra line at the end of readme.

dev-install.sh
Changing he uuid-js filr to 0.7.5 for frontend.
Change-Id: I28415a3d75d13e829626122e4bc587f189598e9f
=> Related-Bug: #1473857

webroot/js/core-constants.js, webroot/js/slickgrid-utils.js, webroot/js/views/AccordianView.js, webroot/js/views/ContrailView.js, webroot/js/views/FormCheckboxView.js, webroot/js/views/FormDropdownView.js, webroot/js/views/FormInputView.js, webroot/js/views/FormMultiselectView.js, webroot/js/views/SectionView.js, webroot/templates/core.common.tmpl
Closes-Bug: #1483527
Change-Id: Ie0b7cd14d657acf3c49a237638cd2cd8f3648181
=> MVC Related changes in form_view files

webroot/css/contrail.custom.css, webroot/css/contrail.layout.css, webroot/js/contrail-common.js, webroot/js/contrail-elements.js, webroot/js/core-formatters.js, webroot/js/core-utils.js, webroot/js/handlebars-utils.js, webroot/js/models/DonutChartModel.js, webroot/js/models/LineBarWithFocusChartModel.js, webroot/js/models/LineWithFocusChartModel.js, webroot/js/views/DetailsView.js, webroot/js/views/DonutChartView.js, webroot/js/views/LineBarWithFocusChartView.js, webroot/js/views/WizardView.js
Bootstrap Modal keyup issue
1. Fixed condition where modal onEnter action were getting called on hit of space bar key
Look and Feel for web-storage
1. Fixed legends visibility for LineCharts
2. Enhanced rendering for DonutChart and other basic look and feel
3. Fixed Detail Expansion advancedOption logic
Wizard related issues
1. Added a function check if the knockout binding exist
2. Enhanced contrailWizard to make sure that load events are called after init events
Change-Id: Iadba89354aa604a540e2033e5e17cbccde1fc951
=> Closes-bug: #1489296, Closes-Bug: #1490736, Partial-Bug: #1490734

webroot/css/contrail.elements.css, webroot/js/common/core.app.utils.js, webroot/js/common/core.constants.js, webroot/js/common/core.views.default.config.js, webroot/js/handlers/ContrailRemoteDataHandler.js, webroot/js/models/DonutChartModel.js, webroot/js/models/LineBarWithFocusChartModel.js, webroot/js/models/LineWithFocusChartModel.js, webroot/js/models/QueryAndModel.js, webroot/js/models/QueryFormModel.js, webroot/js/models/QueryOrModel.js, webroot/js/views/GridView.js, webroot/js/views/QueryFormView.js, webroot/js/views/QuerySelectView.js, webroot/js/views/QueryWhereView.js, webroot/js/views/WidgetView.js, webroot/templates/core.common.tmpl
1) Code cleanup for Where Clause
2) Other minor bug fixes
Change-Id: Ic30f132a533a45fc42e629ddac034c3645d01b7e
=> Partial-bug: #1492052

webroot/css/contrail.custom.css, webroot/css/contrail.elements.css, webroot/js/common/core.constants.js, webroot/js/common/core.labels.js, webroot/js/common/core.messages.js, webroot/js/common/core.views.default.config.js, webroot/js/common/qe.grid.config.js, webroot/js/common/qe.utils.js, webroot/js/models/QueryAndModel.js, webroot/js/models/QueryFormModel.js, webroot/js/models/QueryOrModel.js, webroot/js/views/FormCollectionView.js, webroot/js/views/GridView.js, webroot/js/views/QueryFilterView.js, webroot/js/views/QueryFormView.js, webroot/js/views/QueryWhereView.js, webroot/templates/core.common.tmpl
Added virtual machines tab in vrouter details page
- Fixed broken test-cases
- Fixed issues on networking monitoring
- Created a parser unit test under controller commons
Move query-engine pages to MVC
- In filters operators are available specific to fields
- Where clause style changes
- Ability to select grid columns in object logs
- Changed the color sequence for query queue and line chart of QE
- Add default fields to select clause of flow and system log queries
Changed director structure of network monitoring module such that it is similar to other modules
Change-Id: Ide83585f5a4e0aebba95e1abdfc5cdcbe85e8c9a
=> Partial-Bug: #1492052, #1506851

webroot/js/common/core.utils.js
Change-Id: I2ec383a2eb0a3cd25688097d018b977c43694334
Partial-Bug: #1455188
=> Fixed the Global Alerts

webroot/css/contrail.custom.css
1)CSS changes for Ports page and Service instances
Change-Id: Ibe5a27aad4b6cc452086119b62d505ecd1184870
=> Related-Bug: #1542183 Look and feel improvement in Ports page

webroot/css/contrail.custom.css, webroot/js/common/core.app.utils.js, webroot/js/common/qe.grid.config.js, webroot/js/views/GridView.js, webroot/js/views/QueryResultLineChartView.js, webroot/js/views/TabsView.js, webroot/js/views/ZoomScatterChartView.js
- Fixed expansion of grid on click of header and added expansion link pane while collapsed
- Fixed close of Query Results on toggle of badge on Query Queue
- Fixed positioning of chart message inside ZoomScatterChart
- Fixed BlankDoubleClick on emptyMessage in GraphView
- Removed packet capture action cog from Flow Grid NM pages
- Added cog action cell for Analyze Session action
Change-Id: I4e900850cef338e14453f9c23f3271e141381fed
=> Partial-Bug: #1530242 - Usability Fixes

webroot/test/ui/js/co.test.init.js
- fixed issue with JointJS graph on Chrome borwser.
Change-Id: Ic13ca01b36769c95d3a4b95bc63565d4ff5c9617
=> Related-Bug: #1476413 test infra bug fixes

webroot/js/analyzer-utils.js
Change-Id: I4efaba2a8d12e03d4947b3d248fa576f53c95979
Related-bug: #1331944
(cherry picked from commit cf67925fa66b516fa48815da7e413e6c792fb4ea)
=> Core changes for Tab Interface packet capture

src/serverroot/orchestration/plugins/openstack/nova.api.js, src/serverroot/orchestration/plugins/openstack/openstack.api.js
Add handler for 2.1 in nova code.
In API Version list, while comminicating with nova, start from the higher
version and if fails then to the next available version.
Change-Id: I433c6fe785aeaca3ec0e0aa45bdd21cf4e942703
=> Closes-Bug: #1606550

webroot/css/contrail.components.css, webroot/css/contrail.theme.css, webroot/css/contrail.theme.elements.css, webroot/css/contrail.theme.layout.css, webroot/html/dashboard.tmpl, webroot/js/contrail-elements.js, webroot/js/contrail-load.js, webroot/js/handlers/HelpHandler.js
- Fixed Modal issues where on move of modal, it used to get closed.
- Fixed keyup events for modal.
- Moved Help to Breadcrumbs.
- Fixed issure related to triggering of event for help soon after the login.
- Fixed disabling of help on click of backdrop.
Change-Id: I5cc6985c9b03a207264580d995d76eafc6d5a666
=> Closes-Bug: #1613366, Partial-Bug: #1613467

webroot/common/ui/css/contrail.components.css, webroot/common/ui/css/contrail.theme.elements.css, webroot/common/ui/templates/core.common.tmpl, webroot/js/common/core.utils.js
- Fixed alignment issue for details view on Monitor Infra pages
- Fixed display:inline issues for System Info widget on Mon Infra dashboard
Change-Id: I10ebcfa3ac5fcd208759e3bf710b4652e568b896
Partial-Bug: #1617989.
=> Fixed Alignment issues due to Bootstrap upgrade.

.csslintrc, .eslintignore, .eslintrc.json
Add rc files for JS and CSS linters
Change-Id: I0da2317bbc652e9f77471e2dffa65fcafe4c18e2
Related-Bug: #1621196
=> Add Linting Runtime Configurations

webroot/js/handlers/ContentHandler.js
Check if the page hash present in browser is applicable for the
logged-in user role and if not set the default hash/page for the logged-in user role
Change-Id: Ic076ce90e0d5a0f6adf2ce691d40aad1bf565d82
(cherry picked from commit 5b6a81c9bb70111fa4dba0422e6749c7a9a86e04)
=> Related-Bug: #1594301

webroot/reports/qe/ui/css/qe.main.css
Change-Id: I615c653ee3538aa6a4c81ed4b4f06e7993143367
=> Partial-Bug: #1637614 Fixed Filter clause layout issue styles

webroot/reports/udd/ui/js/views/WidgetView.js
* Fix corrupted chart if it's rendered behind the scene.
Change-Id: I9aa715a1613f7cedf288c7b255b4b3e5e7e92f4d
Closes-Bug: #1643106
=> Chart Visualization isn't Drawn Properly
